### PR TITLE
Translations of page

### PR DESCRIPTION
**Pull request by raynanfernandes**

### CODE REVIEW

**Comment by raynanfernandes** [comment]
https://jam.dev/c/8a1fc6ef-b941-4bb2-884b-d000e748b532

**Comment by Toledodev** [comment]
@raynanfernandes resolve os conflitos ai

**Review by Toledodev — CHANGES_REQUESTED** [review]
conflito

**Comment by raynanfernandes** [comment]
Resolução de conflitos feita

**Pull request merged**
